;[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]
;[]								   []
;[]		Exp09_1.asm : Music Play Program		   []
;[]								   []
;[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]
;
;		Designed and programmed by Duck-Yong Yoon in 2006.
;
;------------------------------------------------
;	Include Header File
;------------------------------------------------
.nolist
.include "m2561def.inc"			; ATmega2561 definition file
.list

;====================================================================
;	Main Program
;====================================================================
.cseg
	.org	0x0000
	LDI	AH,high(RAMEND)		; initialize SP
	LDI	AL,low(RAMEND)
	OUT	SPH,AH
	OUT	SPL,AL

	CALL	INIT_MCU		; initialize MCU and kit
	CALL	D50MS			; wait for system stabilization
	CALL	INIT_LCD		; initialize text LCD

	CALL	LCD_HOME1		; display title
	CALL	LCD_STRING
	.db	" * MUSIC PLAY * ",0,0

;------------------------------------------------
;	Music 1 : Children's Song - "Pongdang Pongdang"
;------------------------------------------------
LOOP:	CALL	LCD_HOME2		; display title
	CALL	LCD_STRING
	.db	"PongdangPongdang",0,0

	LDI	AL,4			; tempo = 4
	CALL	SET_TEMPO
	CALL	MIC			; line 1
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIC
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE16
	CALL	MIA
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE8
	CALL	MIC
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIC
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE16
	CALL	MIA
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE8
	CALL	MIA			; line 2
	CALL	NOTE4
	CALL	MIG
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE4
	CALL	MIG
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	MIC
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE4
	CALL	MIA			; line 3
	CALL	NOTE8D
	CALL	MIA
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	REST8
	CALL	MIG
	CALL	NOTE8D
	CALL	MIG
	CALL	NOTE16
	CALL	MIE
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	MIC
	CALL	NOTE4D
	CALL	REST8
	CALL	MID			; line 4
	CALL	NOTE8D
	CALL	MIE
	CALL	NOTE16
	CALL	MIC
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE4
	CALL	MID
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE16
	CALL	MIF
	CALL	NOTE16
	CALL	MIE
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	MIC
	CALL	NOTE4D
	CALL	REST8
	CALL	D1SEC

;------------------------------------------------
;	Music 2 : Pop Song - "Young Girl, Age 18"
;------------------------------------------------
	CALL	LCD_HOME2		; display title
	CALL	LCD_STRING
	.db	"     Age 18     ",0,0

	LDI	AL,3			; tempo = 3
	CALL	SET_TEMPO
	CALL	MIG			; line 1
	CALL	NOTE4D
	CALL	MIG
	CALL	NOTE16
	CALL	MIA
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIC
	CALL	NOTE4
	CALL	HIC
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE16
	CALL	HID
	CALL	NOTE16
	CALL	HIC
	CALL	NOTE8
	CALL	MIB
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE2
	CALL	MIG			; line 2
	CALL	NOTE4D
	CALL	MIG
	CALL	NOTE16
	CALL	MIA
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIC
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	MID
	CALL	NOTE2
	CALL	MIG			; line 3
	CALL	NOTE4D
	CALL	MIG
	CALL	NOTE16
	CALL	MIA
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIC
	CALL	NOTE4
	CALL	HIC
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE16
	CALL	HID
	CALL	NOTE16
	CALL	HIC
	CALL	NOTE8
	CALL	MIB
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE2
	CALL	MIG			; line 4
	CALL	NOTE8
	CALL	HIE
	CALL	NOTE4
	CALL	HIC
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8D
	CALL	HIC
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE2
	CALL	MIG			; line 5
	CALL	NOTE4D
	CALL	HIE
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE4
	CALL	MIG
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIC
	CALL	NOTE2D
	CALL	REST8
	CALL	MIG			; line 6
	CALL	NOTE4D
	CALL	HIG
	CALL	NOTE8
	CALL	HIE
	CALL	NOTE4
	CALL	HID
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE2D
	CALL	MIG			; line 7
	CALL	NOTE4D
	CALL	MIG
	CALL	NOTE16
	CALL	MIA
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIC
	CALL	NOTE4
	CALL	HIC
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE16
	CALL	HID
	CALL	NOTE16
	CALL	HIC
	CALL	NOTE8
	CALL	MIB
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE2
	CALL	MIG			; line 8
	CALL	NOTE8
	CALL	HIE
	CALL	NOTE4
	CALL	HIC
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8D
	CALL	HIC
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE2
	CALL	D1SEC

;------------------------------------------------
;	Music 3 : Old Song - "Come back to Triangle Rotary"
;------------------------------------------------
	CALL	LCD_HOME2		; display title
	CALL	LCD_STRING
	.db	"Triangle Rotary ",0,0

	LDI	AL,5			; tempo = 5
	CALL	SET_TEMPO
	CALL	MIC			; prelude
	CALL	NOTE4
	CALL	MIC
	CALL	NOTE16
	CALL	MID
	CALL	NOTE16
	CALL	MIE
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE16
	CALL	HIE
	CALL	NOTE4D
	CALL	HID
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE4
	CALL	MIA
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE16
	CALL	MIE
	CALL	NOTE16
	CALL	MIA
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE2
	CALL	HIC
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE16
	CALL	HIC
	CALL	NOTE16
	CALL	MIA
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE4
	CALL	MIG
	CALL	NOTE16
	CALL	MIE
	CALL	NOTE16
	CALL	MID
	CALL	NOTE16
	CALL	MIE
	CALL	NOTE16
	CALL	MIC
	CALL	NOTE2D
	CALL	REST8			; line 1
	CALL	MIC
	CALL	NOTE8
	CALL	MIC
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE4
	CALL	MIG
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE1
	CALL	MIE
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HIE
	CALL	NOTE4
	CALL	HID
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HID
	CALL	NOTE2D
	CALL	REST8
	CALL	HIE			; line 2
	CALL	NOTE4D
	CALL	HID
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE4
	CALL	MIA
	CALL	NOTE16
	CALL	HIC
	CALL	NOTE16
	CALL	MIA
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE16
	CALL	REST8
	CALL	MIE
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE16
	CALL	MIA
	CALL	NOTE16
	CALL	HIC
	CALL	NOTE16
	CALL	MIA
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE2
	CALL	REST8
	CALL	LOA
	CALL	NOTE8
	CALL	LOA
	CALL	NOTE8
	CALL	MIC
	CALL	NOTE8
	CALL	MID
	CALL	NOTE4
	CALL	MIE
	CALL	NOTE16
	CALL	MID
	CALL	NOTE16
	CALL	MIC
	CALL	NOTE16
	CALL	LOA
	CALL	NOTE16
	CALL	MIC
	CALL	NOTE2D
	CALL	REST8
	CALL	MID			; line 3
	CALL	NOTE4D
	CALL	MIE
	CALL	NOTE8
	CALL	MID
	CALL	NOTE4
	CALL	MIC
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	REST8
	CALL	MIE
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE2
	CALL	REST8
	CALL	MIG
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8
	CALL	HIE
	CALL	NOTE4
	CALL	HID
	CALL	NOTE16T
	CALL	HIE
	CALL	NOTE16T
	CALL	HID
	CALL	NOTE16T
	CALL	HIC
	CALL	NOTE16
	CALL	HID
	CALL	NOTE16
	CALL	HIE
	CALL	NOTE2D
	CALL	REST8
	CALL	HIF			; line 4
	CALL	NOTE4D
	CALL	HIE
	CALL	NOTE8
	CALL	HID
	CALL	NOTE4
	CALL	HIC
	CALL	NOTE4
	CALL	REST8
	CALL	MIA
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE4
	CALL	MIA
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE8
	CALL	REST8
	CALL	MIE
	CALL	NOTE16
	CALL	MIE
	CALL	NOTE16
	CALL	MID
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE4
	CALL	MIE
	CALL	NOTE16T
	CALL	MIF
	CALL	NOTE16T
	CALL	MIE
	CALL	NOTE16T
	CALL	MID
	CALL	NOTE8
	CALL	MIC
	CALL	NOTE2D
	CALL	D1SEC

;------------------------------------------------
;	Music 4 : Country Song - "Chil-Gab Mountain"
;------------------------------------------------
	CALL	LCD_HOME2		; display title
	CALL	LCD_STRING
	.db	"  Chil-Gab San  ",0,0

	LDI	AL,4			; tempo = 4
	CALL	SET_TEMPO
	CALL	HIG			; prelude line 1
	CALL	NOTE16
	CALL	HIAX
	CALL	NOTE16
	CALL	HIG
	CALL	NOTE2
	CALL	HIG
	CALL	NOTE16
	CALL	HIF
	CALL	NOTE16
	CALL	HID
	CALL	NOTE16
	CALL	HIF
	CALL	NOTE16
	CALL	HIG
	CALL	NOTE16
	CALL	HIAX
	CALL	NOTE16
	CALL	HIG
	CALL	NOTE2D
	CALL	HID
	CALL	NOTE16
	CALL	HIF
	CALL	NOTE16
	CALL	HID
	CALL	NOTE2
	CALL	HID
	CALL	NOTE16
	CALL	HID
	CALL	NOTE16
	CALL	HIC
	CALL	NOTE16
	CALL	HID
	CALL	NOTE16
	CALL	HIG
	CALL	NOTE16
	CALL	HIF
	CALL	NOTE16
	CALL	HID
	CALL	NOTE2D
	CALL	REST32
	CALL	MID			; prelude line 2
	CALL	NOTE4D
	CALL	MID
	CALL	NOTE8
	CALL	MIF
	CALL	NOTE8
	CALL	MID
	CALL	NOTE16
	CALL	MIF
	CALL	NOTE16
	CALL	MIG
	CALL	NOTE2
	CALL	MIAX
	CALL	NOTE4
	CALL	MIG
	CALL	NOTE2
	CALL	HIG
	CALL	NOTE16
	CALL	HIF
	CALL	NOTE16
	CALL	HID
	CALL	NOTE16
	CALL	HIF
	CALL	NOTE16
	CALL	HIG
	CALL	NOTE16
	CALL	HIAX
	CALL	NOTE16
	CALL	HIG
	CALL	NOTE2
	CALL	REST8
	CALL	HID			; line 1
	CALL	NOTE4
	CALL	HID
	CALL	NOTE2
	CALL	HID
	CALL	NOTE16
	CALL	HIF
	CALL	NOTE16
	CALL	HID
	CALL	NOTE16
	CALL	HIC
	CALL	NOTE16
	CALL	HID
	CALL	NOTE2
	CALL	HIC
	CALL	NOTE8
	CALL	MIAX
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8
	CALL	MIAX
	CALL	NOTE8T
	CALL	MIA
	CALL	NOTE8T
	CALL	MIG
	CALL	NOTE8T
	CALL	MID
	CALL	NOTE2
	CALL	REST8
	CALL	MID			; line 2
	CALL	NOTE8
	CALL	MIF
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE8
	CALL	MIAX
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE2
	CALL	HIC
	CALL	NOTE8T
	CALL	MIAX
	CALL	NOTE8T
	CALL	HIC
	CALL	NOTE8T
	CALL	HID
	CALL	NOTE1
	CALL	REST4
	CALL	HID			; line 3
	CALL	NOTE4
	CALL	HID
	CALL	NOTE4
	CALL	HIF
	CALL	NOTE4
	CALL	HIG
	CALL	NOTE2
	CALL	HIF
	CALL	NOTE4
	CALL	HID
	CALL	NOTE4
	CALL	HIF
	CALL	NOTE4
	CALL	HID
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HID
	CALL	NOTE2
	CALL	REST8
	CALL	HIC			; line 4
	CALL	NOTE8
	CALL	MIAX
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8
	CALL	MIAX
	CALL	NOTE8T
	CALL	MIA
	CALL	NOTE8T
	CALL	MIG
	CALL	NOTE8T
	CALL	MID
	CALL	NOTE2
	CALL	MIAX
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE1
	CALL	REST4
	CALL	MIA			; line 5
	CALL	NOTE4D
	CALL	MIAX
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	MIAX
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE4D
	CALL	HID
	CALL	NOTE8
	CALL	HID
	CALL	NOTE4
	CALL	MIG
	CALL	NOTE4
	CALL	MIG
	CALL	NOTE4
	CALL	MIG
	CALL	NOTE8
	CALL	MIF
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE2
	CALL	REST4
	CALL	MIG			; line 6
	CALL	NOTE4
	CALL	MIAX
	CALL	NOTE4
	CALL	HIC
	CALL	NOTE4
	CALL	HID
	CALL	NOTE4D
	CALL	HIF
	CALL	NOTE8
	CALL	HIG
	CALL	NOTE8
	CALL	HIF
	CALL	NOTE8
	CALL	HID
	CALL	NOTE1
	CALL	REST4
	CALL	HIG			; line 7
	CALL	NOTE4D
	CALL	HIF
	CALL	NOTE8
	CALL	HIG
	CALL	NOTE8
	CALL	HIF
	CALL	NOTE8
	CALL	HID
	CALL	NOTE2D
	CALL	HIC
	CALL	NOTE8
	CALL	MIAX
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8
	CALL	MIAX
	CALL	NOTE8T
	CALL	MIA
	CALL	NOTE8T
	CALL	MIG
	CALL	NOTE8T
	CALL	MID
	CALL	NOTE2
	CALL	REST8
	CALL	MID			; line 8
	CALL	NOTE8
	CALL	MIF
	CALL	NOTE8
	CALL	MIG
	CALL	NOTE8
	CALL	MIAX
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8
	CALL	HIC
	CALL	NOTE2
	CALL	MIAX
	CALL	NOTE8T
	CALL	HIC
	CALL	NOTE8T
	CALL	MIAX
	CALL	NOTE8T
	CALL	MIG
	CALL	NOTE1
	CALL	REST1
	CALL	D1SEC

;------------------------------------------------
;	Music 5 : Pop Song - "Heo-Gong(Empty Sky)"
;------------------------------------------------
	CALL	LCD_HOME2		; display title
	CALL	LCD_STRING
	.db	"   Empty Sky    ",0,0

	LDI	AL,4			; tempo = 4
	CALL	SET_TEMPO
	CALL	MIA			; line 1
	CALL	NOTE8
	CALL	MIB
	CALL	NOTE8
	CALL	MIFX
	CALL	NOTE4D
	CALL	MIE
	CALL	NOTE16
	CALL	MID
	CALL	NOTE16
	CALL	MIFX
	CALL	NOTE2D
	CALL	MIE
	CALL	NOTE8
	CALL	MIFX
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	LOB
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	LOA
	CALL	NOTE2D
	CALL	MID			; line 2
	CALL	NOTE8
	CALL	LOA
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIFX
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	MIB
	CALL	NOTE2
	CALL	MIFX
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE1
	CALL	REST4
	CALL	MID			; line 3
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	HID
	CALL	NOTE4D
	CALL	HID
	CALL	NOTE8
	CALL	HID
	CALL	NOTE2D
	CALL	MIB
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8
	CALL	MIB
	CALL	NOTE4D
	CALL	MIA
	CALL	NOTE8
	CALL	MIFX
	CALL	NOTE2D
	CALL	MIE			; line 4
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE8
	CALL	MIE
	CALL	NOTE4D
	CALL	MIB
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	MIFX
	CALL	NOTE8
	CALL	MIFX
	CALL	NOTE4D
	CALL	MIE
	CALL	NOTE8
	CALL	MID
	CALL	NOTE1
	CALL	REST4
	CALL	HID			; line 5
	CALL	NOTE8
	CALL	HIE
	CALL	NOTE8
	CALL	HIE
	CALL	NOTE4D
	CALL	HIE
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8
	CALL	HIE
	CALL	NOTE8
	CALL	HIFX
	CALL	NOTE2
	CALL	HIE
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8
	CALL	MIB
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8
	CALL	HIE
	CALL	NOTE8
	CALL	HIFX
	CALL	NOTE8
	CALL	HIE
	CALL	NOTE2D
	CALL	HIFX			; line 6
	CALL	NOTE8
	CALL	HIFX
	CALL	NOTE8
	CALL	HIFX
	CALL	NOTE4D
	CALL	HIE
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8
	CALL	HIE
	CALL	NOTE16
	CALL	HID
	CALL	NOTE16
	CALL	MIB
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	MIFX
	CALL	NOTE4
	CALL	MIB
	CALL	NOTE8
	CALL	HIE
	CALL	NOTE8
	CALL	HID
	CALL	NOTE4
	CALL	MIB
	CALL	NOTE8
	CALL	HID
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE2D
	CALL	LOA			; line 7
	CALL	NOTE8
	CALL	LOB
	CALL	NOTE8
	CALL	MID
	CALL	NOTE4D
	CALL	MIE
	CALL	NOTE8
	CALL	MIFX
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE2
	CALL	MID
	CALL	NOTE8
	CALL	MID
	CALL	NOTE8
	CALL	HID
	CALL	NOTE4D
	CALL	HID
	CALL	NOTE8
	CALL	MIB
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	MIFX
	CALL	NOTE2
	CALL	MIA			; line 8
	CALL	NOTE8
	CALL	HIFX
	CALL	NOTE8
	CALL	HIFX
	CALL	NOTE4
	CALL	HIFX
	CALL	NOTE4
	CALL	HIE
	CALL	NOTE4D
	CALL	HIFX
	CALL	NOTE8
	CALL	MIA
	CALL	NOTE8
	CALL	MIB
	CALL	NOTE8
	CALL	HID
	CALL	NOTE1
	CALL	REST1
	CALL	D1SEC

	JMP	LOOP

;====================================================================
;	Include User Subroutine File
;====================================================================
.include "OK2561.INC"			; OK-2561 I/O and subroutine file
.include "MUSIC2561.INC"		; music subroutine file
